AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Inventory stack with AddProduct Lambda function

Parameters:
  Environment:
    Type: String
    Description: 'Deployment environment (dev, staging, prod).'
    AllowedValues: [dev, staging, prod]
    Default: dev

Resources:
  AddProductLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ChainOptAddProduct-${Environment}"
      Handler: addProduct.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      Role: arn:aws:iam::891376911200:role/ChainOptAddProductRole-dev
      CodeUri: ../build/addProduct.zip
      Environment:
        Variables:
          INVENTORY_TABLE_NAME: !Sub "ChainOptInventory-${Environment}"
  GetAllProductsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ChainOptGetAllProducts-${Environment}"
      Handler: getAllProducts.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      Role: arn:aws:iam::891376911200:role/ChainOptGetAllProductsRole-dev
      CodeUri: ../build/getAllProducts.zip
      Environment:
        Variables:
          INVENTORY_TABLE_NAME: !Sub "ChainOptInventory-${Environment}"

Outputs:
  AddProductLambdaArn:
    Description: ARN of the AddProduct Lambda function
    Value: !GetAtt AddProductLambda.Arn
  GetAllProductsLambdaArn:
    Description: ARN of the GetAllProducts Lambda function
    Value: !GetAtt GetAllProductsLambda.Arn
