AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Orders stack with Lambda functions for ChainOpt orders

Parameters:
  Environment:
    Type: String
    Description: 'Deployment environment (dev, staging, prod).'
    AllowedValues: [dev, staging, prod]
    Default: dev
  LambdaCodeBucket:
    Type: String
    Description: 'S3 bucket for Lambda code'
    Default: ''
  LambdaCodePrefix:
    Type: String
    Description: 'S3 prefix for Lambda code'
    Default: 'lambdas/'

Resources:

  InitializeDBFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "ChainOptInitializeDB-${Environment}"
      Handler: initializeDB.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      Role: !ImportValue
        Fn::Sub: ChainOptInitializeDBLambdaRoleArn-${Environment}
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodePrefix}initializeDB.zip"
      Environment:
        Variables:
          DB_NAME: orders
          SECRET_ID: !Sub "ChainOptRDSCredentials-${Environment}"
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue chainopt-lambda-sg
        SubnetIds: !Split [",", !ImportValue project-chainopt-private-subnets]

  UpdateSecretFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "ChainOptUpdateSecret-${Environment}"
      Handler: updateSecret.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      Role: !ImportValue
        Fn::Sub: ChainOptUpdateSecretLambdaRoleArn-${Environment}
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodePrefix}updateSecret.zip"
      Environment:
        Variables:
          SECRET_ID: !Sub "ChainOptRDSCredentials-${Environment}"

  UpdateSecretCustomResource:
    Type: Custom::UpdateSecret
    Properties:
      ServiceToken: !GetAtt UpdateSecretFunction.Arn
      DBHost: !ImportValue chainopt-rds-endpoint
      DBPort: 5432

  CreateOrderFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "ChainOptCreateOrder-${Environment}"
      Handler: createOrder.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      Role: !ImportValue
        Fn::Sub: ChainOptCreateOrderLambdaRoleArn-${Environment}
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodePrefix}createOrder.zip"
      Environment:
        Variables:
          INVENTORY_TABLE_NAME: !Sub "ChainOptInventory-${Environment}"
          SECRET_ID: !Sub "ChainOptRDSCredentials-${Environment}"
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue chainopt-lambda-sg
        SubnetIds: !Split [",", !ImportValue project-chainopt-private-subnets]

  GetOrdersFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "ChainOptGetOrders-${Environment}"
      Handler: getOrders.handler
      Runtime: nodejs22.x
      Timeout: 10
      MemorySize: 256
      Role: !ImportValue
        Fn::Sub: ChainOptGetOrdersLambdaRoleArn-${Environment}
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Sub "${LambdaCodePrefix}getOrders.zip"
      Environment:
        Variables:
          SECRET_ID: !Sub "ChainOptRDSCredentials-${Environment}"
          ORDERS_TABLE_NAME: !Sub "ChainOptOrders-${Environment}"
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue chainopt-lambda-sg
        SubnetIds: !Split [",", !ImportValue project-chainopt-private-subnets]

Outputs:
  CreateOrderFunctionArn:
    Value: !GetAtt CreateOrderFunction.Arn
    Export:
      Name: !Sub "ChainOptCreateOrderFunctionArn-${Environment}"

  GetOrdersFunctionArn:
    Value: !GetAtt GetOrdersFunction.Arn
    Export:
      Name: !Sub "ChainOptGetOrdersFunctionArn-${Environment}"
