AWSTemplateFormatVersion: '2010-09-09'
Description: Creates base secret for RDS connection

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, staging, prod]
    Default: dev

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "ChainOptRDSCredentials-${Environment}"
      Description: Secret for RDS connection
      GenerateSecretString:
        SecretStringTemplate: '{"username": "chainoptadmin", "dbname": "orders"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
        ExcludePunctuation: true
        ExcludeNumbers: false
        ExcludeUppercase: false
        ExcludeLowercase: false
        RequireEachIncludedType: false
        IncludeSpace: false

  # ✅ Separate resource for the secret policy
  DBSecretResourcePolicy:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref DBSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: secretsmanager:GetSecretValue
            Resource: "*"

Outputs:
  DBSecretName:
    Value: !Ref DBSecret
    Export:
      Name: !Sub "ChainOptRDSCredentials-${Environment}"
